### Validate JWT token
GET http://localhost:4001/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImVtYWlsIjoidXNlcjFAbW9jay5jb20iLCJpYXQiOjE3NjAyODIzMTQsImV4cCI6MTc2MDMxODMxNH0.0-nHEJnWFMhtpGUVxXVgVxkWThGpv2o7dPGgl3V-WhA
Accept: application/json
